name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Déclenche le workflow sur chaque commit/push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Remplacez par la version Node.js utilisée dans votre projet

      - name: Install dependencies
        run: npm install --legacy-peer-deps=true

      - name: Build application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Chemin vers le dossier contenant les fichiers générés
